management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

spring:
  boot:
    admin:
      client:
        url: http://localhost:7070
        instance:
          name: chuck-client-circuit-breaker